export const actionType = {
  ADD_ALL_FOOD: "ADD_ALL_FOOD",
  VIEW_SINGLE_FOOD: "VIEW_SINGLE_FOOD",
  REMOVE_FOOD: "REMOVE_FOOD",
  ADJUST_FOOD_QTY: "ADJUST_FOOD_QTY",
  ADD_TO_CART: "ADD_TO_CART",
};
